services:
  # Webサービスの定義
  - type: web
    name: book-manager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python db_init.py --init-with-seed
    startCommand: gunicorn app:create_app() -b 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: USE_AI_FALLBACK
        value: "true"
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL_NAME
        value: gemini-1.5-flash
    healthCheckPath: /
    autoDeploy: true
    # Renderが静的ファイルをホストできるように設定
    staticPublishPath: ./static
    disk:
      name: book-data
      mountPath: /app/instance
      sizeGB: 1

databases:
  # SQLiteは自己管理するのでデータベースサービスは不要
  # 必要に応じてRenderでPostgreSQLに移行可能
